version: "3"

services:
  secret-manager:
    image: node:16-alpine3.15
    working_dir: /opt/app
    command: sh hack/scripts/run-dev.sh
    environment:
      NODE_ENV: development
    env_file:
      - ./hack/env/.dev-env
    volumes:
      - .:/opt/app
